service: awscodingtest
provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
functions:
  getUsers:
    handler: getUser.handle
    events:
      - http:
          path: github/users/{username}
          method: get
  getRepos:
    handler: getRepos.handle
    events:
      - http:
          path: github/users/{username}/repos
          method: get