service: awscodingtest
provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
functions:
  hello:
    handler: event.handle
    events:
      - http:
          path: event
          method: get
          cors: true
  getUser:
    handler: resources/users/get.handle
    events:
      - http:
          path: github/users/{username}
          method: get
          cors: true
  getRepos:
    handler: resources/repos/get.handle
    events:
      - http:
          path: github/users/{username}/repos
          method: get
          cors: true
  putRepo:
    handler: resources/repos/put.handle
    events:
      - http:
          path: github/repos/{owner}/{repo}
          method: put
          cors: true
